name: sabay_ka
description: A carpooling app for the campus.  
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  gem_kit:
    path: plugins/gem_kit

  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_svg: ^1.1.4
  cached_network_image: ^3.2.0
  share_plus: ^10.0.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.0.13
  pocketbase: ^0.18.1
  get_it: ^8.0.0
  book_my_seat: ^1.0.1
  flutter_config: ^2.0.2
  flutter_custom_tabs: ^2.1.0
  form_validator: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
    - assets/images/cars/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
  
